### ISSUE TITLE
Twice CPU time

### ISSUE THREAD

**Issue by GeekAndProud** [NGenesis/VRCPimaxEyeTracker#1]
I understand that processing eye tracking is going to have a performance impact but should it really be causing my CPU frame times to go from 8ms to 25ms+?

**Comment by NGenesis** [comment]
As far as I can tell the high CPU usage comes from the aSeeVR runtime itself being active rather than the mod.  There is also a noticeable hit in CPU usage when DFR is active for other games.

**Comment by GeekAndProud** [comment]
My eyeY is never greater than 0, even when looking straight upward it's 0 instead of being 1.0

**Comment by GeekAndProud** [comment]
There isn't such a huge impact in performance during calibration and that is using the eye tracking. I have a 5800x and a 6900xt so I have more than enough hardware.

I did some testing and while wearing an avatar without eye tracking my CPU frametime is around 5ms but when using an avatar set up for eye tracking it jumps to 30-35ms...

Due to the above differences my average FPS drops from 90(as my refresh rate is 90hz) to 35, I could probably get 120 fps max if i wanted to run at 150 FOV.

I find it hard to believe that the runtime is at fault here, if this cannot be improved on i might as well return the eye tracking module as performance is unacceptable given my hardware and the HUGE loss in framerate/frametime.

**Comment by Kieaer** [comment]
same issue here.

**Comment by GeekAndProud** [comment]
> same issue here.

https://github.com/benaclejames/VRCFaceTracking
